# Projeto de Deep Learning
### 2021/2

Predição de partidas de futebol da copa américa com base em dados históricos.

In [ ]:
!pip install sklearn tensorflow

# Pegando os dados

In [111]:
import pandas as pd

In [117]:
df = pd.read_csv('data.csv')
df.head()

Data      Casa       Fora  Gols Casa  Gols Fora  Edição     Fase
0  2001-07-11   Equador      Chile        1.0        4.0    2001  Grupo A
1  2001-07-11  Colombia  Venezuela        2.0        0.0    2001  Grupo A
2  2001-07-14     Chile  Venezuela        1.0        0.0    2001  Grupo A
3  2001-07-14  Colombia    Equador        1.0        0.0    2001  Grupo A
4  2001-07-17   Equador  Venezuela        4.0        0.0    2001  Grupo A

## Criando Coluna objetivo

In [118]:
df["Vencedor"] = df.apply(lambda row: 1 if row["Gols Casa"] > row["Gols Fora"] else 0, axis=1)
print(df.shape)
df.head()

(212, 8)


Data      Casa       Fora  Gols Casa  Gols Fora  Edição     Fase  \
0  2001-07-11   Equador      Chile        1.0        4.0    2001  Grupo A   
1  2001-07-11  Colombia  Venezuela        2.0        0.0    2001  Grupo A   
2  2001-07-14     Chile  Venezuela        1.0        0.0    2001  Grupo A   
3  2001-07-14  Colombia    Equador        1.0        0.0    2001  Grupo A   
4  2001-07-17   Equador  Venezuela        4.0        0.0    2001  Grupo A   

   Vencedor  
0         0  
1         1  
2         1  
3         1  
4         1

## Dropando valores nulos

In [119]:
df.dropna(inplace=True)
df.shape

(208, 8)

## Filtrando features

In [132]:
X = df.iloc[:, 1:5].values
y = df.iloc[:, -1:].values
print(f"X: {X[0])}")
print(f"y: {y[:5]}")

X: <class 'numpy.ndarray'>
y: [[0]
 [1]
 [1]
 [1]
 [1]]


## Transformando features categóricas

In [135]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

X[:, 0] = le.fit_transform(X[:, 0])
X[:, 1] = le.fit_transform(X[:, 1])
X

array([[8, 4, 1.0, 4.0],
       [5, 18, 2.0, 0.0],
       [4, 18, 1.0, 0.0],
       [5, 8, 1.0, 0.0],
       [8, 18, 4.0, 0.0],
       [5, 4, 2.0, 0.0],
       [16, 15, 3.0, 3.0],
       [2, 13, 0.0, 1.0],
       [2, 16, 2.0, 0.0],
       [15, 13, 0.0, 0.0],
       [16, 13, 1.0, 0.0],
       [2, 15, 3.0, 1.0],
       [1, 17, 0.0, 1.0],
       [10, 6, 0.0, 1.0],
       [17, 6, 1.0, 1.0],
       [10, 1, 2.0, 0.0],
       [1, 6, 0.0, 4.0],
       [10, 17, 1.0, 0.0],
       [4, 13, 0.0, 2.0],
       [6, 17, 1.0, 2.0],
       [5, 16, 3.0, 0.0],
       [10, 2, 2.0, 0.0],
       [13, 17, 2.0, 1.0],
       [5, 10, 2.0, 0.0],
       [17, 10, 2.0, 2.0],
       [5, 13, 1.0, 0.0],
       [18, 5, 0.0, 1.0],
       [16, 1, 2.0, 2.0],
       [5, 1, 1.0, 0.0],
       [16, 18, 3.0, 1.0],
       [18, 1, 1.0, 1.0],
       [16, 5, 2.0, 2.0],
       [13, 17, 2.0, 2.0],
       [0, 8, 6.0, 1.0],
       [17, 8, 2.0, 1.0],
       [0, 13, 0.0, 1.0],
       [13, 8, 2.0, 1.0],
       [0, 17, 4.0, 2.0],
       [6,

In [140]:
import numpy as np

# convertendo dados para ser usado pelo tensorflow

X[:,0] = X[:,2].astype(np.float64)
X[:,1] = X[:,3].astype(np.float64)
X

array([[1.0, 4.0, 1.0, 4.0],
       [2.0, 0.0, 2.0, 0.0],
       [1.0, 0.0, 1.0, 0.0],
       [1.0, 0.0, 1.0, 0.0],
       [4.0, 0.0, 4.0, 0.0],
       [2.0, 0.0, 2.0, 0.0],
       [3.0, 3.0, 3.0, 3.0],
       [0.0, 1.0, 0.0, 1.0],
       [2.0, 0.0, 2.0, 0.0],
       [0.0, 0.0, 0.0, 0.0],
       [1.0, 0.0, 1.0, 0.0],
       [3.0, 1.0, 3.0, 1.0],
       [0.0, 1.0, 0.0, 1.0],
       [0.0, 1.0, 0.0, 1.0],
       [1.0, 1.0, 1.0, 1.0],
       [2.0, 0.0, 2.0, 0.0],
       [0.0, 4.0, 0.0, 4.0],
       [1.0, 0.0, 1.0, 0.0],
       [0.0, 2.0, 0.0, 2.0],
       [1.0, 2.0, 1.0, 2.0],
       [3.0, 0.0, 3.0, 0.0],
       [2.0, 0.0, 2.0, 0.0],
       [2.0, 1.0, 2.0, 1.0],
       [2.0, 0.0, 2.0, 0.0],
       [2.0, 2.0, 2.0, 2.0],
       [1.0, 0.0, 1.0, 0.0],
       [0.0, 1.0, 0.0, 1.0],
       [2.0, 2.0, 2.0, 2.0],
       [1.0, 0.0, 1.0, 0.0],
       [3.0, 1.0, 3.0, 1.0],
       [1.0, 1.0, 1.0, 1.0],
       [2.0, 2.0, 2.0, 2.0],
       [2.0, 2.0, 2.0, 2.0],
       [6.0, 1.0, 6.0, 1.0],
       [2.0, 1

## Divide o dado em Treino e Teste

In [141]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Criação do modelo 

In [151]:
import tensorflow as tf
ann = tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])



## Treinando o modelo

In [152]:
# Convertendo dados para o tensorflow
X_train = np.asarray(X_train).astype(np.float32)
y_train = np.asarray(y_train).astype(np.float32)

ann.fit(X_train, y_train, batch_size = 32, epochs = 15)

Epoch 1/15
6/6 [==============================] - 1s 3ms/step - loss: 0.6744 - accuracy: 0.6386
Epoch 2/15
6/6 [==============================] - 0s 3ms/step - loss: 0.6605 - accuracy: 0.6627
Epoch 3/15
6/6 [==============================] - 0s 3ms/step - loss: 0.6472 - accuracy: 0.7771
Epoch 4/15
6/6 [==============================] - 0s 3ms/step - loss: 0.6348 - accuracy: 0.8313
Epoch 5/15
6/6 [==============================] - 0s 3ms/step - loss: 0.6229 - accuracy: 0.8313
Epoch 6/15
6/6 [==============================] - 0s 3ms/step - loss: 0.6127 - accuracy: 0.8313
Epoch 7/15
6/6 [==============================] - 0s 3ms/step - loss: 0.6039 - accuracy: 0.8313
Epoch 8/15
6/6 [==============================] - 0s 3ms/step - loss: 0.5953 - accuracy: 0.8313
Epoch 9/15
6/6 [==============================] - 0s 3ms/step - loss: 0.5863 - accuracy: 0.8313
Epoch 10/15
6/6 [==============================] - 0s 3ms/step - loss: 0.5770 - accuracy: 0.8313
Epoch 11/15
6/6 [======================

In [154]:
X_test = np.asarray(X_test).astype(np.float32)

y_pred = ann.predict(X_test)
y_pred

array([[0.4136217 ],
       [0.47106886],
       [0.7985399 ],
       [0.60073066],
       [0.6600599 ],
       [0.656196  ],
       [0.4136217 ],
       [0.5425551 ],
       [0.4866838 ],
       [0.60484254],
       [0.60073066],
       [0.71124506],
       [0.31880432],
       [0.6600599 ],
       [0.3649038 ],
       [0.5023248 ],
       [0.5023248 ],
       [0.71475923],
       [0.28322434],
       [0.3649038 ],
       [0.5425551 ],
       [0.60073066],
       [0.4136217 ],
       [0.60073066],
       [0.4866838 ],
       [0.5425551 ],
       [0.4866838 ],
       [0.47106886],
       [0.27599788],
       [0.60073066],
       [0.31880432],
       [0.60484254],
       [0.83411425],
       [0.1710051 ],
       [0.60484254],
       [0.60073066],
       [0.5023248 ],
       [0.4136217 ],
       [0.27599788],
       [0.38175678],
       [0.5425551 ],
       [0.60484254]], dtype=float32)

## Predizendo os dados de Teste

In [159]:
y_pred = [ i[0] for i in y_pred.tolist()]

In [161]:
y_test = [ i[0] for i in y_test.tolist()]

In [163]:
previsões = [1 if i > 0.5 else 0 for i in y_pred]

## Criando matrix de confusão

In [164]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, previsões)
print(cm)

[[18  3]
 [ 0 21]]


## Salvando o modelo

In [166]:
ann.save("model")

INFO:tensorflow:Assets written to: model/assets
